
# PUMP

- alias: garden pump off
  trigger:
    platform: state
    entity_id: switch.pump
    from: 'off'
    to: 'on'
    for:
      seconds: 60
  condition:
    condition: state
    entity_id: switch.pump
    state: 'on'
  action: 
    service: 'switch.turn_off'
    entity_id: switch.pump

- alias: garden pump on
  trigger:
    platform: time
    minutes: 1
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.garden_soil_humidity
        state: 'off'
      - condition: state
        entity_id: binary_sensor.garden_water
        state: 'on'
      - condition: state
        entity_id: switch.pump
        state: 'off'
        for:
          seconds: 30

  action:
    service: 'switch.turn_on'
    entity_id: switch.pump

- alias: check garden pump off
  trigger:
    platform: state
    entity_id: switch.pump
    state: 'on'
    for:
      seconds: 300
  action:
    service: 'switch.turn_off'
    entity_id: switch.pump
